services:
  - type: web
    name: simple-sql-site
    env: python
    plan: free
    buildCommand: "pip install -r appointment_site/requirements.txt"
    startCommand: "gunicorn app:app"
    rootDir: appointment_site
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString
