services:
  - type: web
    name: govisit-hello-world
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    rootDir: appointment_site